// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zivwebkawwotchmgxpqf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InppdndlYmthd3dvdGNobWd4cHFmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1MzkxMDAsImV4cCI6MjA3MDExNTEwMH0.A9QRL4g7lRU82sFY0Op9CgRtmphwA3GsLfvs8E6nyxY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});